name = "RootedTrees"
uuid = "47965b36-3f3e-11e9-0dcf-4570dfd42a8c"
authors = ["Hendrik Ranocha <mail@ranocha.de>"]
version = "2.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
RecipesBase = "1"
julia = "1"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[targets]
test = ["Plots", "StaticArrays", "Test", "UnicodePlots"]
